# Numpy

numpy는 수치해석용 파이썬 패키지를 의미. 리스트에 담긴 데이터를 행렬로 만들어 관리할 때 사용.

- 조건1 : 행렬 안에 있는 모든 값은 같은 타입이어야 한다
- 조건2 : 관리하는 원소의 개수를 변경할 수 없다.

### 패키지 import

In [1]:
import numpy as np

### 1차원 배열(행렬) 만들기

In [2]:
list1 = [10,20,30,40,50]
array1 = np.array([10,20,30,40,50])


print(list1)
print(array1)
print(type(list1))
print(type(array1))



[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'list'>
<class 'numpy.ndarray'>


### 벡터 연산

In [3]:
# 리스트에서 곱하기는 개수를 늘림
print(list1 * 3)

# numpy에서 곱셈은 계산작용
print(array1 * 3)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 30  60  90 120 150]


In [4]:
print(array1)
print(array1 + 10)
print(array1 - 10)
print(array1 * 10)
print(array1 // 10 )

[10 20 30 40 50]
[20 30 40 50 60]
[ 0 10 20 30 40]
[100 200 300 400 500]
[1 2 3 4 5]


In [5]:
list2 = [10,20,30,40,50]
list3 = [1,2,3,4,5]
print(list2 + list3)

[10, 20, 30, 40, 50, 1, 2, 3, 4, 5]


In [6]:
array2 = np.array([10,20,30,40,50])
array3 = np.array([1,2,3,4,5])
print(array2 + array3)

[11 22 33 44 55]


In [7]:
print(array2 == 30)

[False False  True False False]


In [8]:
print(list2 == 30)

False


### 2차원 배열 생성

In [9]:
list1 = [
        [1,2,3],
        [4,5,6],
        ]
list1

[[1, 2, 3], [4, 5, 6]]

In [10]:
array1 = np.array([
                [1,2,3],
                [4,5,6]
                ])
print(array1)

[[1 2 3]
 [4 5 6]]


In [11]:
# 행의 개수
len(array1)

2

In [12]:
# 열의 개수
len(array1[0])

3

### 다양한 타입

- 행렬은 다양한 타입의 값을 담을 수 없다.
- 행렬을 생성할 때 다양한 타입을 넣으면 해당 타입을 모두 표현이 가능한 형태로 변환됨


In [13]:
list1 = [10, 11.11, True, "안녕하세요"]
array1 = np.array([10, 11.11, True, "안녕하세요"])
print(list1)
print(array1)

[10, 11.11, True, '안녕하세요']
['10' '11.11' 'True' '안녕하세요']


In [14]:
# 0으로 채워진 행렬을 생성
# 0. -> 실수 형태
array2 = np.zeros(5)
array2

array([0., 0., 0., 0., 0.])

In [15]:
array3 = np.zeros([2,3])
array3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
array4 = np.zeros([2,3], dtype='i')
array4

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [17]:
array5 = np.ones([2,3], dtype = 'i')
array5

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [18]:
# 쓰레기 값이 담긴 행렬 생성, 무슨 값이 나올지 모른다
array6 = np.empty([2,3])
array6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# 특정 범위의 값을 가지고 있는 행렬을 생성

# 0~10-1까지
array7 = np.arange(10)
print(array7)

# 3~ 12-1까지
array8 = np.arange(3, 12)
print(array8)

# 3~ 12-1, 2씩 증가
array9 = np.arange(3,12,2)
print(array9)

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11]
[ 3  5  7  9 11]


In [20]:
# 특정 범위 안에서 원하는 만큼의 숫자를 추출해 행렬로 생성
# (시작값, 끝 값, 원하는 개수)로 균등 분할
array10 = np.linspace(0, 100, 5)
print(array10)

[  0.  25.  50.  75. 100.]


### 전치 연산 (행과 열을 바꾼다)

In [21]:
array1 = np.array([[10,20,30],[40,50,60]])
array2 = array1.T

print(array1)
print(array2)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


### 배열의 크기를 변형

In [22]:
array1 = np.arange(12)
print(array1)

# 배열을 3행 4열로 만든다.
array2 = array1.reshape(3,4)
print(array2)
# 배열을 3차원으로 만든다.
array2 = array1.reshape(3,2,2)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [23]:
# 행렬을 배열로 만든다.
array3 = array2.flatten()
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])