In [1]:
import numpy as np

In [2]:
array1 = np.array([10,20,30,40,50])
array2 = np.array([
                [1,2,3],
                [4,5,6]
                ])
print(array1)
print(array2)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]


In [3]:
print(f' array1 차원 수 : {array1.ndim}')
print(f' array1 행렬 수 : {array1.shape}')
print(f' array2 차원 수 : {array2.ndim}')
print(f' array2 행렬 수 : {array2.shape}')

 array1 차원 수 : 1
 array1 행렬 수 : (5,)
 array2 차원 수 : 2
 array2 행렬 수 : (2, 3)


### 배열의 인덱싱

In [4]:
list1 = [10,20,30,40,50]
list2 = [[10,20,30],[40,50,60]]
list3 = np.array([10,20,30,40,50])
list4 = np.array([[10,20,30],[40,50,60]])

In [5]:
# 0번째 값을 가지고 온다

print(list1[0])
print(array1[0])

# 2번째 값을 가져온다
print(list1[2])
print(array1[2])

# -1번째 값을 가져온다
print(list1[-1])
print(array1[-1])

# -3번째 값을 가져온다
print(list1[-3])
print(array1[-3])

10
10
30
30
50
50
30
30


In [6]:
# 0행 0열 값을 가져온다.

print(list2[0][0])
print(array2[0, 0])

# 1행 2열 값을 가져온다

print(list2[1][2])
print(array2[1,2])

# 마지막행 마지막 열 값을 가지고 온다
print(list2[-1][-1])
print(array2[-1,-1])

10
1
60
6
60
6


In [8]:
# True, False를 이용한 값 가져오기
# []안에 True와 False가 담긴 행렬을 넣으면 True 자리에 해당하는 값만 가져온다
array1 = np.array([10,20,30,40,50])

array3 = np.array([True, False, True, False, True])
print(array1[array3])

[10 30 50]


In [9]:
array2 = np.array([
                [1,2,3],
                [4,5,6]
                ])

array4 = np.array([[True, False, True],
                   [False, True, False]])
print(array2[array4])

[1 3 5]


In [10]:
# list1에서 20보다 큰 값만 가져온다

print(array1)
print(array1 > 20)
print(array1[array1 >20])

[10 20 30 40 50]
[False False  True  True  True]
[30 40 50]


### 배열 슬라이싱


In [ ]:
list1 = [10,20,30,40,50]
list2 = [[10,20,30],[40,50,60]]
array1 = np.array([10,20,30,40,50])
array2 = np.array([[10,20,30],[40,50,60]])



In [12]:
#일부만 가져온다
# 시작인덱스 : 끝인덱스 - 1
print(list1[1:4])
print(list2[0:1][0:1])
print(list2[0:1])

[20, 30, 40]
[[10, 20, 30]]
[[10, 20, 30]]


In [13]:
print(array1[1:4])

[20 30 40]


In [14]:
# 처음부터 3-1까지
print(array1[:3])

# 1~ 끝까지
print(array1[1:])

[10 20 30]
[20 30 40 50]


In [15]:
array3 = np.array([
            [1,2,3,4,5], 
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25]
])

print(array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [16]:
# 1~ 4-1행, 1~ 4-1열
print(array3[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [17]:
# 0~ 4-1행, 1~ 끝열
print(array3[:4, 1:])

[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]


In [18]:
# 1행, 모든열
print(array3[1])

# 1~ 4-1행, 모든열
print(array3[1:4])

# 3번째열 전체 행
print(array3[:,2])

# 2번째행 전체 열
print(array3[1,:])



[ 6  7  8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18 23]
[ 6  7  8  9 10]
