In [1]:
import numpy as np

In [2]:
data = np.array(  [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]  )
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
data.shape

(4, 3)

In [4]:
# 본질적으로는 dataframe에서 iloc[] 속성과 같다
# 컴마가 없으면 행만, 컴마가 있어야 열 부분의 조건을 달 수 있다


# data[행,열]

In [5]:
# 0행
data[0]

array([1, 2, 3])

In [6]:
# 복수개 선택

# 0행과 3행 선택
# 매트릭스가 2차원으로 생성됨
data[[0,3]]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [9]:
data[0] # 1차원

array([1, 2, 3])

In [10]:
# 복수개의 대괄호 ; 무조건 매트릭스로 형성됨
data[[0]]

array([[1, 2, 3]])

In [11]:
# 0행 1열 생성
data[0,1] 

2

In [14]:
# 1행부터 끝까지 슬라이싱
data[1:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
# 1행부터 끝까지, 2열만 슬라이싱
data[1:, 2]

array([ 6,  9, 12])

In [18]:
# 1행부터 끝까지, 1열부터 끝까지
data[1:, 1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [19]:
# 모든 행, 열은 1열부터 끝까지
data[:, 1:]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [20]:
# 모든행, 0열과 2열 슬라이싱
data[:,[0,2]]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])